[package]
name = "settings-form"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
egui-cha.workspace = true
egui-cha-ds.workspace = true
eframe.workspace = true
egui.workspace = true
