[package]
name = "vj-mock"
version = "0.1.0"
edition = "2021"

[dependencies]
egui-cha = { path = "../../crates/egui-cha", features = ["eframe"] }
egui-cha-ds = { path = "../../crates/egui-cha-ds" }
eframe = "0.31"
tracing-subscriber = "0.3"
