[package]
name = "vj-mock"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
egui-cha.workspace = true
egui-cha-ds = { workspace = true, features = ["studio"] }
eframe.workspace = true
tracing-subscriber = "0.3"
