[package]
name = "vj-mock"
version = "0.1.0"
edition = "2021"

[dependencies]
egui-cha.workspace = true
egui-cha-ds = { workspace = true, features = ["studio"] }
eframe.workspace = true
tracing-subscriber = "0.3"
